In [ ]:
import numpy as np


In [ ]:
# creating an array
first = np.array ([1,2,3,4,6,5,7])
print (first)
print(type(first))

[1 2 3 4 6 5 7]
<class 'numpy.ndarray'>


In [ ]:
data = np.array([1,2,3,5,6,7])

In [ ]:
a= np.mean(data)
print(a)

4.0


In [ ]:
#shape of array
print(first.shape)
print(type(first.shape))

(7,)
<class 'tuple'>


In [ ]:
#dimension of array
print(first.ndim)

1


In [ ]:
for i in range (0,first.__len__()):
  print(first[i])

1
2
3
4
6
5
7


In [ ]:
#input diffrent datatype in array
first=np.array([100,3.4,"hello",True])
print(first)
#print output one by one
for i in range(0,first.__len__()):
    print(first[i])

['100' '3.4' 'hello' 'True']
100
3.4
hello
True


In [ ]:
print(type(first))
print("dimension of array is\t",first.ndim)
print("shape of array is\t",first.shape)

<class 'numpy.ndarray'>
dimension of array is	 1
shape of array is	 (4,)


In [ ]:
#indexing in python
arr1=np.array([10,20,30,40])
print(arr1)
print(arr1[0])
print(arr1[-1])

[10 20 30 40]
10
40


In [ ]:
print("from the begining")
for i in range(0,arr1.__len__()):
    print(arr1[i])

In [ ]:
print("from the end")
for i in range(-1,-(arr1.__len__()+1),-1):
    print(arr1[i])

In [ ]:
first=np.arange(3)
print(first)
print("enter 3 numbers")
for i in range(0,first.__len__()):
    first[i]=int(input())
print("Displaying all the numbers")
for i in range(0,first.__len__()):
    print(first[i])


In [ ]:
print("dimension of array is\t",first.ndim)
print("shape of array is\t",first.shape)

In [ ]:
#creating an empty array
empty_array = np.empty((3, 3))
print("Empty Array:")
print(empty_array)

In [ ]:
# Create a full array (all elements set to a specific value, e.g., 7)
full_array = np.full((3, 3), 7)
print("\nFull Array:")
print(full_array)

In [ ]:
# Create an array
arr = np.array([1, 2, 3])
# Number of elements in the array
size = arr.size
print(arr)
print(size)
print(arr.ndim)
print(arr.itemsize)# Length of one array element in bytes
print(arr.nbytes)# Total bytes consumed by the elements

In [ ]:
# Length of one array element in bytes
item_size = arr.itemsize

# Total bytes consumed by the elements
total_bytes = arr.nbytes

print("Size of the array:", size)
print("Length of one array element in bytes:", item_size)
print("Total bytes consumed by the elements of the array:", total_bytes)


In [ ]:
#  here we've passed list of list
first=np.array([[10,20,30],[40,50,60]])
print(first)

[[10 20 30]
 [40 50 60]]


In [ ]:
for i in range(0,first.__len__()):
    for j in range(0,first[i].__len__()):
        print(first[i][j],"\t",end="")
    print("\n")

print("Type of the array is",type(first))
print("dimension of array is\t",first.ndim)
print("shape of array is\t",first.shape)

10 	20 	30 	

40 	50 	60 	

Type of the array is <class 'numpy.ndarray'>
dimension of array is	 2
shape of array is	 (2, 3)


In [ ]:
# how to accept values from user inside two-d array

from numpy import *
list=[]
print("how many rows")
rownum=int(input())
print("how many cols")
colnum=int((input()))
print("Enter\t",rownum*colnum," values")
for i in range(1,(rownum*colnum)+1):
        num=int(input())
        list.append(num)




In [ ]:
mainarray=array([list])
print(mainarray)

In [ ]:
#reshape is used to reshape the list to conver  it to array
mainarray=mainarray.reshape(rownum,colnum)

print(mainarray)

In [ ]:
# initialize one-d array with zero
first=np.zeros((1,4))                             # one row , 4 columns
print(first)
print("\n")

# initialize two-d array with zeros

second=np.zeros((3,4))                            # 3 rows and 4 columns

print(second)

In [ ]:
# initialize one-d and 2d array  with one

import numpy as np
first=np.ones((1,4))                             # one row , 4 columns

print(first)
print("\n")

# initialize two-d array with zeros

second=np.ones((3,4))                            # 3 rows and 4 columns

print(second)

In [ ]:
# initialize arrays with a specific number

import numpy as np

first=np.full((1,4),20)         #  1 row, 4 columns , all should be initialized with 20
print(first)

print("\n")

second=np.full((3,2),15)        #  3 rows, 2 columns, all should be initialized with 15
print(second)

In [ ]:
# arange to give range of numbers
import numpy as np
first=np.arange(20,25)    # here 25 is exclusive
print(first)

# start with 10, increment by 2 and here 20 is exclusive

second=np.arange(10,20,2)
print(second)



In [ ]:
""" If you only use the arange function, it will output a
 one-dimensional array. To make it a two-dimensional array,
  chain its output with the reshape function. """

import numpy as np
 # 3 rows,3 cols ,  10 to 90 values with 10 as a skip value
first=np.arange(10,91,10).reshape(3,3)
print(first)


In [ ]:
# array with strings and chars

first=np.full((1,4),"hello")
print(first)
print("\n")
second=np.array(['A','B','C','D','E','F'])
print(second)
print("\n")
third=np.full((3,2),'A')
print(third)

In [ ]:
# initialize numpy array with random numbers
import numpy as np

# range for random numbers is 1 to 100 and 10
# is how many random numbers to be generated

first=np.random.randint(1,100,10)
print(first)
print("Double Dimension array")

second=np.random.randint(1,100,12).reshape(3,4)
print(second)

In [ ]:
""" randint() function generates new set of random numbers everytime. If we want to fix the generation of random numbers,
we should use "seed()" function by passing any number as an argument. """

from numpy import *

random.seed(15)    # this can be any number  , try commenting this

first=random.randint(1,100,12)
print(first)     # no matter how many times we execute the code, it will display same set of numbers
print("size of the array is\t",first.size)



In [ ]:
 # checking the shape of numpy array

import numpy as np
first=np.array([100,200,300,400,500,600])
print(first)
print(first.shape)

print("let's check with double dimension array")
second=np.array([[10,20,30],[40,50,60]])
print(second)
print(second.shape)

print("Let's convert one-d array's shapes")
first.shape=(2,3)
print(first)
print("Let's convert two-d array's shape")
second.shape=(3,2)
print(second)
print(second.ndim)

In [ ]:
#  "intersect1d()" to find out common elements between two arrays

import numpy as np
first=np.array([4,5,8,12,15])
second=np.array([11,15,4,8,9])
third=np.intersect1d(first,second)
print(third)


In [ ]:
#  "setdiff1d()" to find out unique elements in first array
# result is always sorted

import numpy as np
first=np.array([4,25,8,32,15])
second=np.array([11,25,1,2,4,8,9])
  #  unique elements inside "first"  array
third=np.setdiff1d(first,second)
print(third)
print("\n")
fourth=np.setdiff1d(second,first) # unique elements inside "second" array
print(fourth)


In [ ]:


myarr=np.array([10,10,20,20,30,30])
print("main array is")
print(myarr)
myarr1=np.unique(myarr)
print("unique value in array",myarr1)

In [ ]:
myarr2=np.array([[1,1],[2,3]])
print(myarr2)
myarr3=np.unique(myarr2)
print(myarr3)

In [ ]:
myarr=np.array([10,10,20,20,30,30])
print("main array is")
print(myarr)
myarr1=np.unique(myarr)
print(myarr1)

In [ ]:
myarr2=np.array([[1,1],[2,3]])
print(myarr2)


In [ ]:
myarr3=np.unique(myarr2)
print(myarr3)

In [ ]:
# Arrays
array1 = np.array([0, 10, 20, 40, 60, 80])
array2 = np.array([10, 30, 40, 50, 70])

# Set exclusive-or
result = np.setxor1d(array1, array2)

print("Unique values that are in only one (not both) of the input arrays:")
print(result)

In [ ]:
import numpy as np

# Sample array
arr = np.array([1, 2, 3, 4])
print("Original array")
print(arr)

# Repeat 2 times
repeat_2 = np.tile(arr, 2)
print("Repeating 2 times")
print(repeat_2)
print(type(repeat_2))

# Repeat 3 times
repeat_3 = np.tile(arr, 3)
print("Repeating 3 times")
print(repeat_3)



In [ ]:

first=np.array([10,20,30,40])
print(first)                    #  array will be printed
np.save("myarray",first)
first=None
print(first)                    # None, no need to worry, we can load the saved array
second=np.load("myarray.npy")   # extension "npy" mandatory
print(second)

# ***About Axis***

In [ ]:
"""in 2d array

axis 0 means
	chopping something from top to bottom

axis 1 means
	chopping something from left to right
"""

myar=np.array([[10,20,30],[40,50,60],[70,80,90]])

print("entire sum")
print(np.sum(myar))
print("axis 0 sum")
print(np.sum(myar,axis=0))  # chopping something from top to bottom
print("axis 1 sum")
print(np.sum(myar,axis=1))  # chopping something from left to right

entire sum
450
axis 0 sum
[120 150 180]
axis 1 sum
[ 60 150 240]


In [ ]:
"""in 3d array

axis 0 means
	no. of 2d arrays

axis 1 means
	chopping something from top to bottom

axis 2 means
	chopping something from left to right
"""
import numpy  as np

myar=np.array([10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27])

myar.shape=(2,3,3)
print(myar)



In [ ]:
# put 2nd two d array after first 2d array and then sum
print(np.sum(myar))
print(np.sum(myar,axis=0))
"""
[[10 11 12]   [[19 20 21]     [[29 31 33]
 [13 14 15] +  [22 23 24]  =   [35 37 39]
 [16 17 18]]    [25 26 27]]     [41 43 45]]
"""

In [ ]:
 # it's like axis=0 in 2d array ,
 #chopping something from top to bottom within each 2d array
print("with axis 1")
print(np.sum(myar,axis=1))
"""
[10 11 12] + [13 14 15] + [16 17 18] = [39 42 45]
[19 20 21] + [22 23 24] + [25 26 27] = [66 69 72]
"""


In [ ]:
# it's like axis=1 in 2d array,
# chopping something from left to right within each 2d array
print("with axis 2")
print(np.sum(myar,axis=2))
"""
[10+11+12, 13+14+15, 16+17+18] = [33, 42, 51]
[19+20+21, 22+23+24, 25+26+27] = [60, 69, 78]
"""

# **Stack**

### **1d arrays with hstack,vstack,dstack,zero,one axis stack**

In [ ]:
arr1= np.array([10,20,30])
arr2=np.array([40,50,60])

hstack1=np.hstack((arr1,arr2))
print("Let's print horizontal stack")
print(hstack1)
"""
[10 20 30 40 50 60]   horizontally stacked
"""


In [ ]:
vstack1=np.vstack((arr1,arr2))
print("Let's print vertical stack")
print(vstack1)
"""
[[10 20 30]
 [40 50 60]]         vertically stacked

"""

#  np.stack((arr1,arr2),axis=2)  # not possible


In [ ]:
dstack1=np.dstack((arr1,arr2))
print("Let's print d stack")
print(dstack1)

"""
[[[10 40]
  [20 50]
  [30 60]]]    depth i.e. 0th element of both the arrays will be joined ,then 1st element of both the arrays will be joined and so on
"""


In [ ]:

zerostack=np.stack((arr1,arr2),axis=0)  #  top to bottom
print("let's print axis-0 stack")
print(zerostack)

"""
[[10 20 30]
 [40 50 60]]  it's a double dimension array, first array is placed at 0th row and second at 1st row

"""



In [ ]:

onestack=np.stack((arr1,arr2),axis=1)  #  left to right
print("let's print axis-1 stack")
print(onestack)

"""
[[10 40]
 [20 50]
 [30 60]]
		it like first array is taken and stacked at 0th column and second is stacked at 1st column
"""

## **2D arrays with hstack,vstack,dstack,zero,one axis stack**


In [ ]:
arr1= np.array([[10,20,30],[40,50,60]])
arr2=np.array([[70,80,90],[100,110,120]])

hstack1=np.hstack((arr1,arr2))
print("Let's print horizontal stack")
print(hstack1)
"""
[[ 10  20  30  70  80  90]     horizontally stacked
 [ 40  50  60 100 110 120]]
"""


In [ ]:
arr1= np.array([[10,20,30],[40,50,60]])
arr2=np.array([[70,80,90],[100,110,120]])

vstack1=np.vstack((arr1,arr2))
print("Let's print vertical stack")
print(vstack1)
"""
[[ 10  20  30]			vertically stacked
 [ 40  50  60]
 [ 70  80  90]
 [100 110 120]]

"""

In [ ]:

arr1= np.array([[10,20,30],[40,50,60]])
arr2=np.array([[70,80,90],[100,110,120]])

dstack1=np.dstack((arr1,arr2))
print("Let's print d stack")
print(dstack1)

"""
[[[ 10  70]    first array's 0th element second's 0th element and so on....
  [ 20  80]
  [ 30  90]]

 [[ 40 100]
  [ 50 110]
  [ 60 120]]]
"""

In [ ]:
arr1= np.array([[10,20,30],[40,50,60]])
arr2=np.array([[70,80,90],[100,110,120]])


zerostack=np.stack((arr1,arr2),axis=0)
print("let's print axis-0 stack")
print(zerostack)

"""
since it is going to create 3d array, in 3d array first is no. of 2d arrays
so both 2d arrays are just stacked one below another

[[[ 10  20  30]
  [ 40  50  60]]

 [[ 70  80  90]
  [100 110 120]]]
"""


In [ ]:
arr1= np.array([[10,20,30],[40,50,60]])
arr2=np.array([[70,80,90],[100,110,120]])

onestack=np.stack((arr1,arr2),axis=1)
print("let's print axis-1 stack")
print(onestack)

"""

since it is going to create 3d array, in 3d array second is no. of rows
so both 2d arrays 0th rows and 1st rows are stacked one below another

[[[ 10  20  30]        # 0th row of first 2d array
  [ 70  80  90]]       # 0th row of second 2d array

 [[ 40  50  60]        # 1st row of first 2d array
  [100 110 120]]]      # 1st row of second 2d array

"""



In [ ]:
arr1= np.array([[10,20,30],[40,50,60]])
arr2=np.array([[70,80,90],[100,110,120]])

twostack=np.stack((arr1,arr2),axis=2)
print("let's print axis-2 stack")
print(twostack)

"""

since it is going to create 3d array, in 3d array third is no. of cols
hence 1st 2d arrays 0th row and 2nd 2d arrays 0th row are placed in the
columns 0 and 1 respectively. Similarly 1st 2d arrays 1st row and 2nd
2d arrays 1st row are placed in the columns 0 and 1 respectively.

[[[ 10  70]
  [ 20  80]
  [ 30  90]]

 [[ 40 100]
  [ 50 110]
  [ 60 120]]]


"""

## **One more example**

In [ ]:
import numpy as np

arr1=np.array([[1,2,3],[4,5,6]])
arr2=np.array([[7,8,9],[10,11,12]])
arr3=np.array([[13,14,15],[16,17,18]])

hstack=np.hstack((arr1,arr2,arr3))
print("this is hstack")
print(hstack) # each 2d array's individual rows are stacked horizontally



dstack=np.dstack((arr1,arr2,arr3))
print("this is dstack")
print(dstack) # each 2d array's individual member is stacked together

stack_0=np.stack((arr1,arr2,arr3),axis=0)
print("this is 0 stack")
print(stack_0)  # in 3d array, axis 0 means no. of 2d arrays
# here we have 3 2d arrays , so they are stacked one below other

stack_1=np.stack((arr1,arr2,arr3),axis=1)
print("this is 1 stack")
print(stack_1)  # in 3d array axis 1 is similar to axis 0 of 2d array
# i.e. top to bottom
# each 2d array's 0th rows are stacked from top to bottom , then 1st rows and so on

stack_2=np.stack((arr1,arr2,arr3),axis=2)
print("this is 2 stack")
print(stack_2) # in 3d array axis 2 is similar to axis 1 of 2d array
# i.e. left to right
# each 2d array's 0th row will be placed in the 0th column, 1st and 2nd column respectively
# in the first generated 2d array
# each 2d array's 1th row will be placed in the 0th column, 1st and 2nd column respectively
# in the second generated 2d array.

print(stack_2.ndim)
print(stack_2.shape)

### **Numpy_Mathematical**

In [ ]:
first=np.array([10,20,30])
second=np.array([40,50,60])
third=np.sum((first,second),axis=0)     # top to bottom
# [50 70 90]
print(third)
print("\n")
fourth=np.sum((first,second),axis=1)    # left to right
# [ 60 150]
print(fourth)

In [ ]:
arr=np.array([[1,2,3,4],
             [2,3,4,5],
             [7,8,9,10]])
arr1=np.sum(arr,axis=1)   # left to right sum
# 1+2+3+4   2+3+4+5   7+8+9+10
print(arr1)

arr2=np.sum(arr,axis=0)  # top to bottom sum
# 1+2+7     2+3+8     3+4+9     4+5+10
print(arr2)

eg 14 b

In [ ]:
import numpy as np

fourth=np.array([[10,20,30],[40,50,60]])
fifth=np.array([[70,80,90],[100,110,120]])
sixth=np.sum((fourth,fifth),axis=0)
"""
in case of 3d array axis 0 means no.of 2d arrays
here we have 2 2d arrays , so in axis 0 what happens
is second 2d array is placed behind 1st 2d array and sum is performed
on each and every element i.e. 10 is added to 70, 20 is added to 80 and so on....
"""
""" [[ 80 100 120]
     [140 160 180]] """
print(sixth)



In [ ]:
eighth=np.sum((fourth,fifth),axis=1)
"""
in 3d array axis 1 is similar to axis 0 of 2d array i.e. top to bottom
so each 2d arrays sum will be calculated based of top to bottom pattern
it means 10 is added to 40, 20 is added to 50 and so..on
"""
""" [[ 50  70  90]
 [170 190 210]] """

print(eighth)

In [ ]:
ninth=np.sum((fourth,fifth),axis=2)
"""
in 3d array axis 2 means axis 1 of 2d array i.e. left to right
so each 2d arrays sum will be calculated on left to right pattern
it means 10+20+30   40+50+60   70+80+90   100+110+120
"""
print(ninth)
""" [[ 60 150]
 [240 330]] """

**example** 15

In [ ]:
import numpy as np
print("Let's try with 3 arrays")
a = np.array([[10,20,30],
              [40,50,60]])

b = np.array([[ 70, 80, 90],
              [100,110,120]])

c = np.array([[ 5,  9, 11],
              [15, 17, 18]])


In [ ]:
print("output of axis=0")
d=np.sum((a,b,c),axis=0)
print(d)
"""
Row 1, Col 1 → [10 + 70 + 5] = 85
Row 1, Col 2 → [20 + 80 + 9] = 109
Row 1, Col 3 → [30 + 90 + 11] = 131

Row 2, Col 1 → [40 + 100 + 15] = 155
Row 2, Col 2 → [50 + 110 + 17] = 177
Row 2, Col 3 → [60 + 120 + 18] = 198

[[ 85 109 131]
 [155 177 198]] """

In [ ]:
print("output of axis=1")
e=np.sum((a,b,c),axis=1)
print(e)
"""
Now summing along axis=1:

For a: [10+40, 20+50, 30+60] = [50, 70, 90]

For b: [70+100, 80+110, 90+120] = [170, 190, 210]

For c: [5+15, 9+17, 11+18] = [20, 26, 29]

 [[ 50  70  90]
 [170 190 210]
 [ 20  26  29]] """

In [ ]:
print("output of axis=2")
f=np.sum((a,b,c),axis=2)
print(f)
"""
Step 3: Work it out
For array a:
Row1: 10 + 20 + 30 = 60
Row2: 40 + 50 + 60 = 150

For array b:
Row1: 70 + 80 + 90   = 240
Row2: 100 + 110 + 120 = 330

For array c:
Row1: 5 + 9 + 11 = 25
Row2: 15 + 17 + 18 = 50

 [[ 60 150]
 [240 330]
 [ 25  50]] """

**Indexing_Slicing_One-d_ array**

In [ ]:
from numpy import *

first=array([10,20,30,40])
# indexing from left to right

print(first[0],"\t",first[1],"\t",first[2],"\t",first[3])

# indexing from right to left

print("\n")
print(first[-1],"\t",first[-2],"\t",first[-3],"\t",first[-4])

In [ ]:
from numpy import *

first=array([10,20,30,40,50,60])
print(first)
print("\n")
second=first[2:4]    #  4 is exclusive
print("after slicing")
print(second)
third=first[1:5:2]     #  2 is a skip value,  if not given it is by default 1
print("\n")
print(third)
fourth=first[3:]       #  start from the 3rd position and go till end
print("\n")
print(fourth)
print("\n")
fifth=first[:4]        #  start from 0 and go till 3 ,  4 is exclusive
print(fifth)
sixth=first[-2:]       #  last two elements   , start from second last and go till end
print("\n")
print(sixth)
print("\n")
seventh=first[:-2]     # start from zero and go till second last,   second last is exclusive
print(seventh)
eighth=first[-4:-1]    # start from -4 i.e. number 30  and go till last , last is exclusive
print("\n")
print(eighth)

## Indexing_Slicing_Two-**d_array**

example 1


In [ ]:
from numpy import *

first=array([[10,20,30],[40,50,60],[70,80,90]])
print("from left to right")
print(first[0][0])
print(first[0][1])
print(first[0][2])
print(first[1][0])
print(first[1][1])
print(first[1][2])
print(first[2][0])
print(first[2][1])
print(first[2][2])
print("from right to left")
print(first[-1][-1])
print(first[-1][-2])
print(first[-1][-3])
print(first[-2][-1])
print(first[-2][-2])
print(first[-2][-3])
print(first[-3][-1])
print(first[-3][-2])
print(first[-3][-3])


### **Example 1 Slicing**

In [ ]:
from numpy import *

first=array([[10,20,30],
             [40,50,60],
             [70,80,90]])
# slicing syntax
#  arrayname [row range,col range]

second=first[2:3]     # start from 0th row and go till 2nd row,   2 is exclusive  this is only for row as you haven't given column
print(second)


In [ ]:
third=first[:2,1:3]  #  row 0 to 1    column 1 to 2  , 3 is exclusive
print(third)

### Example 2 **Slicing**

In [ ]:
from numpy import *

random.seed(8)
first=random.randint(1,500,30).reshape(6,5)
print("array created is")
print(first)


In [ ]:
print("from the 2nd row")
print(first[2:])            #  from 2nd row
print("\n")

In [ ]:
print(first[2:,3])          #  from 2nd row and only 3rd column
print("\n")

In [ ]:
print(first[2:,2:])         #  from 2nd row and from 2nd column
# let's extract  459  62  and 19
print("\n")

In [ ]:
print(first[3:,1:2])
# let's extract 340 361 86 317 156 and 109
print("\n")

In [ ]:
print(first[1:4,2:4])
print("\n")

In [ ]:
# let's extract  459  156  and 109
print(first[3:4,1:4])

# Numpy mutable or immutable

### example **1**

In [ ]:
# numpy array elements are mutable but numpy as an object is immutable
# first+1  creates a new numpy object in which changes can be seen

import numpy as np
first=np.array([10,20,30])
print(first,"\t",id(first))
second=first+1      #  this is like immutable
first[0]=34         #  array elements can be changed
print(first,"\t",id(first))
print(second,"\t",id(second))


Example 2

In [ ]:
# how to make numpy array read only
import numpy as np


first=np.array([10,20,30])
first.flags.writeable = False
print(first,"\t",id(first))
second=first+1      #  no problem here
# first[0]=34         # ValueError: assignment destination is read-only
print(first,"\t",id(first))
print(second,"\t",id(second))


### **Sort Numpy**

Example 1

In [ ]:
a = np.array([12, 15, 10, 1])
print("Array before sorting",a)
a.sort()
print("Array after sorting",a)

Example 2


In [ ]:
import numpy as np

# sort without any axis

a = np.array([[12, 25],
              [30, 18]])
arr1 = np.sort(a, axis=None)
print("\nAlong None axis : \n", arr1)


In [ ]:
# sort along the first axis
a = np.array([[12, 25], [30, 18]])
arr1 = np.sort(a, axis=0) # top to bottom
# 12 will be compared with 30, 25 will be compared with 18
print("Along 0 axis : \n", arr1)

In [ ]:
a = np.array([[12, 25],
              [30, 18]])
arr1 = np.sort(a, axis=1) # left to right
# 12 will be compared to 25, 30 will be compared to 18
print("\nAlong 1 axis : \n", arr1)

In [ ]:
a = np.array([[12, 25],
              [30, 18]])
print("Reverse order top to bottom\n")
arr1 = -np.sort(-a, axis=0)
print(arr1)

In [ ]:
a = np.array([[12, 25],
              [30, 18]])
print("Reverse order left to right\n")
arr1 = -np.sort(-a, axis=1)
print(arr1)

here for descending order we have said

a = np.array([[12, 25], [30, 18]])

print("Reverse order axis 0\n") arr1 = -np.sort(-a, axis=0) print(arr1)

why two minus(-) signs are required here? one for np.sort and other for "a"

First Minus (-a): This negates the elements of the array a. So, for example, the array [[12, 25], [30, 18]] becomes [[-12, -25], [-30, -18]]. This transformation effectively flips the values, allowing larger original values to become smaller (in terms of their negated values).

np.sort(-a, axis=0): Now, when you apply np.sort to the negated array, it sorts the values in ascending order. For the transformed array, this means the larger original values will appear first.

Second Minus (-np.sort(-a, axis=0)): Finally, you negate the sorted result again to return it to the original scale. This gives you the values in descending order.

In [ ]:
myar = np.array([[[10, 20, 30],
                  [4, 50, 6]],

                 [[70, 8, 90],
                  [65, 110, 12]]])
print(myar)


In [ ]:
myar = np.array([[[10, 20, 30],
                  [4, 50, 6]],

                 [[70, 8, 90],
                  [65, 110, 12]]])
print("Ascending order 3d array axis 0")
arr1 = np.sort(myar, axis=0)
print(arr1)
"""
in 3d array axis 0 means no. of 2d arrays. Since we have 2 2d arrays
each and every element of 1st 2d array will be compared with 2nd 2d array

10 will be compared with 70, 20 will be with 8, 30 will be with 90
4 will be with 65, 50 will be with 110, 6 will be with 12
"""

In [ ]:
myar = np.array([[[10, 20, 30],
                  [4, 50, 6]],

                 [[70, 8, 90],
                  [65, 110, 12]]])

print("Ascending order 3d array axis 1")
arr1 = np.sort(myar, axis=1)
"""
in 3d array axis 1 means axis 0 of 2d array i.e. top to bottom
so in each 2d array elements will be compared on top to bottom basis
i.e.
10 will be compared with 4, 20 will be with 50, 30 will be compared with 6
70 will be compared with 65, 8 will be compared with 110, 90 will be compared with 12"""

print(arr1)

In [ ]:
myar = np.array([[[10, 20, 30],
                  [4, 50, 6]],

                 [[70, 8, 90],
                  [65, 110, 12]]])

print("Ascending order 3d array axis 2")
arr1 = np.sort(myar, axis=2)
"""
in 3d array axis 2 means axis 1 of 2d array which means left to right
so each individual array of each 2d array will be compared from left to right
i.e. 10 will be compared with 20 and 30
4 will be compared with 50 and 60
and so on....
"""
print(arr1)

In [ ]:
myar = np.array([[[10, 20, 30],
                  [4, 50, 6]],

                 [[70, 8, 90],
                  [65, 110, 12]]])
print("Reverse order 3d array axis 0\n")
arr1 = -np.sort(-myar, axis=0)
print(arr1)


In [ ]:
myar = np.array([[[10, 20, 30],
                  [4, 50, 6]],

                 [[70, 8, 90],
                  [65, 110, 12]]])
print("Reverse order 3d array axis 1\n")

arr1 = -np.sort(-myar, axis=1)
print(arr1)


In [ ]:
myar = np.array([[[10, 20, 30],
                  [4, 50, 6]],

                 [[70, 8, 90],
                  [65, 110, 12]]])
print("Reverse order 3d array axis 2\n")

arr1 = -np.sort(-myar, axis=2)
print(arr1)

# **Filtering_in_Numpy**

Eg 1


In [ ]:
arr = np.array([5,8,9,11,12,16])
print(arr)
print(arr[[True,False,True,False,True,False]])

In [ ]:
arr = np.array([5,8,9,11,12,16])
print(arr)
print(arr%4==0)  #  it prints  [False  True False False  True  True]

In [ ]:
arr = np.array([5,8,9,11,12,16])
print(arr)
print(arr[(arr%4==0)]) # it's like arr[[False  True False False  True  True]]

In [ ]:
arr = np.array([5,8,9,11,12,16])
print(arr)
print(arr[(arr>=9) & (arr<=15)])

In [ ]:
arr = np.array([5,8,9,11,12,16])
print(arr)
print(arr[(arr%3==0) | (arr%11==0)])

In [ ]:
arr = np.array([5,8,9,11,12,16])
print(arr)
#filter for values that are equal to 2, 3, 5, or 12
print(np.isin(arr,[2, 3, 5, 12]))

In [ ]:
arr = np.array([5,8,9,11,12,16])
print(arr)
print(arr[np.isin(arr,[2, 3, 5, 12])])

Example_3_Using_Mask


In [ ]:
# Using mask

import numpy as np

# making a numpy array
array1 = np.array([num for num in range(10, 50)])

print("Original array")
print(array1)

# defining mask based on two conditions:
# array element must be greater than 22
# and must be a divisible by 2
mask = (array1 > 22) & (array1 % 2 == 0)

# making new array on conditions
array2 = array1[mask]
print("New array")
print(array2)


Example_4_Using_Iterative_method

In [ ]:
# Using iterative method

import numpy as np

# making a numpy array
array1 = np.array([x for x in range(11, 40)])

print("Original array")
print(array1)

# making a blank list
mylist = []

for x in array1:
    # applying two conditions: number is divisible by 2 and is greater than 15
    if x % 2 == 0 and x > 15:
       mylist.append(x)

# Converting new list into numpy array
array2 = np.array(mylist)
print("New array")
print(array2)

Example_5_Using_Lambda

In [ ]:
# del list
""" if the below code shows
TypeError: 'list' object is not callable is a classic Python gotcha.
It means that somewhere in your code (before this cell),
you overwrote the built-in list with something else
 (probably by doing something like this):
 """

In [ ]:
# Using Lambda
# making a numpy array
array1 = np.array([num for num in range(1,30)])

print("Original array")
print(array1)

In [ ]:
# using lambda to apply condition
mylist = list(filter(lambda x: x > 15 and x % 3 == 0 and x % 10 != 0, array1))

# Converting new list into numpy array
array2 = np.array(mylist)
print("New array")
print(array2)

In [ ]:
print("Using list comprehension for numpy filtering")
mylist1=[x for x in array1 if x%5==0]
array2=np.array(mylist1)
print(array2)

Example_6_Filter_Two_D_array

In [ ]:
array1= np.arange(12).reshape(3,4)
print("original array is\n")
print(array1)
result = array1[array1 > 5]

In [ ]:
print("Filter values from array:",result)
result1=array1[(array1<10) & (array1%3==0)]
print(result1)

Example_7_Filter_Two_D_array_different_axis

In [ ]:
# axis=0 top to bottom
# axis=1 left to right
a = np.arange(12).reshape((3, 4))
print(a)

In [ ]:
"""
np.all() method return True if all the values fulfills the condition.
This return value maps with the original array to give the filtered values

: means all rows
"""

print(a[:, np.all(a < 10, axis = 0)])


In [ ]:
""" np.any() method return true if any of the values fulfill the condition.
 This return value maps with the original array to give the filtered values.
 : means all the rows
 """
print(a[:,np.any(a < 10, axis = 0)])

In [ ]:
"""
axis=1 means left to right
: here means all the columns
"""
print(a[:,np.any(a > 8, axis = 0)])

In [ ]:
print(a[np.any(a < 10, axis = 1),:])

In [ ]:
print(a[np.all(a < 10, axis = 1),:])

In [ ]:
print("selected rows")
print(a[1:3,np.any(a > 8, axis = 0)])   # 1 to 2 rows  , top to bottom


In [ ]:
print("selected columns")
print(a[np.all(a < 10, axis = 1),:2])    # 0 to 1 columns , left to right

# **Concate_Numpy**

NumPy stack() vs concatenate()

In [ ]:
""" NumPy stack() vs. concatenate()

the concatenate() function joins elements of two arrays along an existing axis while the stack() function joins the two arrays along a new axis. This means when we use "stack",the resulting array will have one more dimension than the input arrays.
 """
import numpy as np

a = np.array([1,2])
b = np.array([3,4])

c = np.concatenate((a,b)) # return 1-D array
d = np.stack((a,b)) # return 2-D array
print("concat output")
print(c)
print("stack output")
print(d)

Concat 1d arrays

In [ ]:
# concate 1 d arrays

import numpy as np
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
arr3=np.concatenate((arr1,arr2)) #  it will make one single array containing arr1 and arr2 values
print(arr3)    #  [1 2 3 4 5 6]


concate and stack 2d arrays with axis=0

In [ ]:
# concate and stack 2d arrays with axis=0
# axis=0 means from top to bottom

import numpy as np
arr1=np.array([[1,2,3],[4,5,6]])
arr2=np.array([[7,8,9],[10,11,12]])
arr3=np.concatenate((arr1,arr2),axis=0) #  keep arr1 and arr2 one below other,and create 2d array
print("output of concat")
print(arr3)

"""
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

"""
print("dimension of new array after concat function is\t",arr3.ndim)
print("shape of new array after concat function is\t",arr3.shape)
print()

In [ ]:

print()
print("output of stack")
arr4=np.stack((arr1,arr2),axis=0)    #  keep arr1 and arr2 one below other,and create 3d array
print(arr4)

"""
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]

"""
print("dimension of new array after stack function is\t",arr4.ndim)
print("shape of new array after stack function is\t",arr4.shape)


axis 2 not allowed in concat

In [ ]:
# with stack
# axis 0,1 and 2 all are possible for stack in the following case


import numpy as np
arr1=np.array([[1,2,3],
               [4,5,6]])
arr2=np.array([[7,8,9],
               [10,11,12]])
print(arr1.ndim)
print(arr2.ndim)
arr3=np.stack((arr1,arr2),axis=0)
print(arr3)
print(arr3.ndim)
print(arr3.shape)
print("*********")
arr3=np.stack((arr1,arr2),axis=1)
print(arr3)
print(arr3.ndim)
print(arr3.shape)
print("*********")
arr3=np.stack((arr1,arr2),axis=2)
print(arr3)
print(arr3.ndim)
print(arr3.shape)




In [ ]:
# with concat


arr1=np.array([[1,2,3],[4,5,6]])
arr2=np.array([[7,8,9],[10,11,12]])

in the above case
	np.stack
		axis 0,axis 1 and axis 2 all are possible

	np.concat
		axis 0 and axis 1 are possible
		but axis 2 is not possible,it says
			axis 2 is out of bounds for array of dimension 2
	why it is so?

arr3=np.concatenate((arr1,arr2),axis=0)
print(arr3)
print(arr3.ndim)
print(arr3.shape)


[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

	dimension 2  [ does not change the dimension of the resulting array which is correct as per "concat" method ]
	shape - 4,3


arr3=np.concatenate((arr1,arr2),axis=1)
print(arr3)
print(arr3.ndim)
print(arr3.shape)

[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]

	dimension 2  [ does not change the dimension of the resulting array which is correct as per "concat" method ]

	shape - 2,6


arr3=np.concatenate((arr1,arr2),axis=2) # it will not work, but let's assume it works. now let's see what is the side effect of this.
print(arr3)
print(arr3.ndim)
print(arr3.shape)


1  7
2  8
3  9

4  10
5  11
6  12

	dimension 3  [ it will change the dimension of the resulting array which is not correct as per "concat" method. this should not happen that's why here "axis-2" gives error]
	shape - 2,3,2

in short axis-2 always results into 3d array which concat never supports. Concat works with multiple 2d arrays but result is always the 2d array.

